import { StyleSheet } from 'react-native';

export const C = {
  bg: '#F5F0E1',
  card: '#F5F0E1',
  inset: '#EDE8D9',
  text: '#1A1A1A',
  textSoft: '#7A7568',
  textMuted: '#A09A8A',
  accent: '#1A1A1A',
  success: '#2D8A4E',
  error: '#C44040',
  gold: '#C4A44A',
  shadow: '#B8AF9A',
  highlight: 'rgba(255,255,255,0.85)',
};

export const neu = StyleSheet.create({
  card: {
    backgroundColor: C.card,
    borderRadius: 20,
    padding: 20,
    shadowColor: C.shadow,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 6,
  },
  cardSm: {
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 16,
    shadowColor: C.shadow,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
  inset: {
    backgroundColor: C.inset,
    borderRadius: 14,
    shadowColor: C.shadow,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 0,
  },
  pillBtn: {
    backgroundColor: C.card,
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: 'center' as const,
    shadowColor: C.shadow,
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 4,
  },
  darkBtn: {
    backgroundColor: C.accent,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center' as const,
    shadowColor: C.shadow,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
});
